### ISSUE TITLE
Figure out relationship to diffs-rs

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/similar#1]
Currently this does not use [diffs-rs](https://docs.rs/diffs/0.4.0/diffs/) but it tries to stay largely compatible to it. The reason it's a fork rather than reusing the code comes down to the following reasons at the moment:

* I want to replace the difference.rs crate with this crate and my desire is not to introduce additional dependencies
* The source code of diffs-rs is hard to read and documentation is very, very light
* The diffs-rs source code is tracked as part of pijul which is not a very common tool and it's rather cumbersome to find the source code and issue tracker of it if one runs into issues.

The outcome right now is not super great because it should be possible in theory to create a version of this crate which is reduced to exactly what diffs-rs does.

**Comment by mitsuhiko** [comment]
From the conversation with @P-E-Meunier on a Twitter DM:

> We're working on character encodings at the moment in Pijul, which is closely related to diffs, and would probably benefit you. Note that I don't mind if you fork the project.
>
> I believe my main point is that in addition to this, I would be happy to stop maintaining the diffs crate, and switch Pijul to use similar, and contribute to performance improvements, if it were hosted in Pijul, because a fast diff is crucial for me.

**Comment by mitsuhiko** [comment]
I tried using diffs directly for a test now but I'm currently running into incompatible bounds on the patience diff.

**Comment by P-E-Meunier** [comment]
You mean the `D` type parameter requires `Sized` in the following function?

https://docs.rs/diffs/0.4.1/diffs/patience/fn.diff.html

**Comment by mitsuhiko** [comment]
@P-E-Meunier I have to admit I have troubles reading the trait bounds on that function at the moment. I believe that the current bounds define `S::Output: Sized` which does not work for the usage in this crate.

**Comment by mitsuhiko** [comment]
These crates have diverged too much, I'm going to close this issue is no longer being applicable.
