### ISSUE TITLE
`get_close_matches` type incosistency

### ISSUE THREAD

**Issue by Daggy1234** [mitsuhiko/similar#28]
The `get_close_matches` expects a slice of the type `&[&std::string::String]`, however I have no idea on how one could construct this type. Therefore would a move to the modern `&[&str]` or even just a `&[String]` be possible?

**Comment by mitsuhiko** [comment]
`get_close_matches` does not expect a `&[&String]`, it works with any `DiffableStr`. I think this might be a mistake in using it on your part. Maybe you can reopen this issue with a repro case.
