### ISSUE TITLE
Crash in UnifiedDiff::to_string method

### ISSUE THREAD

**Issue by sv-91** [mitsuhiko/similar#37]
This code crashes or produces incorrect output
```rust   
    let fst = "\u{18}\n\n";
    let snd = "\n\n\r";

    let mut config = similar::TextDiffConfig::default();
    let diff = config.diff_lines(fst, snd);
    let mut output = diff.unified_diff();
    let result = output.context_radius(0).to_string();
    println!("Result:\n{}", result);
```

**Comment by mitsuhiko** [comment]
A `context_radius` of 0 does not make sense. I will add an explicit panic here in the internal function to make it error earlier.

**Comment by sv-91** [comment]
Yes, there are other examples here with different radius but with panic. 
I don't understand, why there is needed explicit panic. I think, this is correct example, and it must work correctly.
You can change first symbol of fst to any other symbol, it doesn't matter

**Comment by mitsuhiko** [comment]
As far as I can tell the example works fine with a non zero radius. I also believe the input data is irrelevant for the particular problem that a radius of `0` causes. What would you expect that a radius of `0` does?
