### ISSUE TITLE
Are implementaions of `to_writer()` and `Display::fmt()` intentionally duplicated for `::udiff::{UnifiedDiff, UnifiedDiffHunk}`?

### ISSUE THREAD

**Issue by nc7s** [mitsuhiko/similar#54]
Take `UnifiedDiff` as an example:

https://github.com/mitsuhiko/similar/blob/2b31f65445df9093ba007ca5a5ae6a71b899d491/src/udiff.rs#L181-L194

https://github.com/mitsuhiko/similar/blob/2b31f65445df9093ba007ca5a5ae6a71b899d491/src/udiff.rs#L298-L314

**Comment by mitsuhiko** [comment]
One is limited to unicode, the other one works for all bytes. That's why there are minor differences between the two. Could probably be written with less repetition, but this was easier.

**Comment by nc7s** [comment]
Hmm, overlooked the difference of `io::Write` and `DiffableStr`, my bad. That in the semantics of both interfaces is also clear after your explanation. Thanks!
