### ISSUE TITLE
pretty_assertions alternative based on similar

### ISSUE THREAD

**Issue by RazrFalcon** [mitsuhiko/similar#6]
[pretty_assertions](https://crates.io/crates/pretty_assertions) is pretty popular and based on `difference.rs` and also abandoned. It would be great to have an alternative or even replace `difference.rs` in the `pretty_assertions` itself.

**Comment by mitsuhiko** [comment]
@RazrFalcon ideally someone tries to reach out to the maintainer of `pretty_assertions` and figures out if the crate can be transferred. I tried to do this for instance with difference.rs but never got a response from the author.

**Comment by RazrFalcon** [comment]
I see. Good. Than we have to wait a bit first. And since you're already aware of it, I will close this one.
