### ISSUE TITLE
How to add this to GitUI?

### ISSUE THREAD

**Issue by LordMoMA** [mitsuhiko/similar#63]
I followed the docs and it did not work.

**Comment by max-sixty** [comment]
Could you give an example of what you tried and the outputs you saw?

(not a maintainer, trying to help though)

**Comment by LordMoMA** [comment]
<img width="747" alt="SCR-20240415-bxvc" src="https://github.com/mitsuhiko/similar/assets/67067729/51a085c1-b139-4d6e-8baf-e9fd7828de96">

Thanks, want this highlight of diff, like diff-so-fancy

**Comment by max-sixty** [comment]
What do you mean that you followed the docs and it did not work?

**Comment by mitsuhiko** [comment]
I'm closing this as this does not seem actionable.
