### ISSUE TITLE
Suitable for large binary files?

### ISSUE THREAD

**Issue by sgmihai** [mitsuhiko/similar#67]
I wan to make a patch file to convert an .mkv file that I remuxed from .m2ts back to the original .m2ts
Such files are 20-70GB large. Would similar work well on these ? The data, video audio streams, is mostly identical, but their distance increases between the two files the further you go forward, because of the mpeg stream redundant packets of data. I tried with xdelta3 and got good results up to a point where the window size was too small for it to keep detecting the identical parts, and no way to increase window size beyond 2GB.

If you think similar could work in this scenario, please give me some sample code on how to best use it. Is there no cli tool based on this at all ? Thanks.

**Comment by mitsuhiko** [comment]
You should be able to use it.  Just use the underling capturing diff functions on the byte vectors.  See this example here for instance: https://github.com/mitsuhiko/similar/blob/main/examples/nonstring.rs
